### ISSUE TITLE
Tile 23100 on 20230310 petal 3 has bright star that appears to corrupt the petal

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#104] opened 2023-03-13 22:10 UTC
Should we mark the petal bad and reprocess?

**Comment by schlafly** [comment] 2023-03-16 00:45
If this is the ordinary case where the problem isn't going away ("the sky is wrong"), we have not been reprocessing these or doing anything special.  We've just accepted them.

**Comment by schlafly** [comment] 2023-04-05 18:54
Marked as good, closing.

**Closed by schlafly** 2023-04-05 18:54 UTC
