### ISSUE TITLE
Fiber on bright star in petal 3 of tileid=5599 from 20231213

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#166] opened 2023-12-15 09:28 UTC
It s a mag=7 star:  `FIBER=1855`, `TARGETID=2252857029951489`, a secondary FAINT_HPM target (a high-proper motion star).

<img width="1381" alt="tmp-tileid5599-fiber1855" src="https://github.com/desihub/desisurveyops/assets/61986357/247fe9d3-94e5-4069-8ff8-97be9e65c5cf">

It messes up half of a region of the petal=3:

<img width="326" alt="tmp-tileid5599-skyzfiber" src="https://github.com/desihub/desisurveyops/assets/61986357/5a9e0c06-b620-4333-9533-ca6ea0fd1861">

Probably we should mark half of the petal as bad, is that is possible?

**Comment by schlafly** [comment] 2023-12-15 09:33
If we mark it bad, we'll probably reobserve this target?  Do we think the faint high proper motion target crossed in front of the bright Tycho target, but would have been fine to observe at some other epoch?

**Comment by araichoor** [comment] 2023-12-15 09:53
"_If we mark it bad, we'll probably reobserve this target?_"
=> ah you re right, sorry!

"_Do we think the faint high proper motion target crossed in front of the bright Tycho target, but would have been fine to observe at some other epoch?_"
=> I don t really know; from the fiberassign file, that target has `PMRA=-8.69, PMDEC=-260.57, REF_EPOCH=2000` (and `GAIA_PHOT_G_MEAN_MAG=20.4).

**Comment by geordie666** [comment] 2023-12-25 08:41
I changed the title, as the problem is on [tile 5599](https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/5599/20231213/tile-qa-5599-thru20231213.png) not 5519.

**Comment by geordie666** [comment] 2023-12-25 08:50
This issue is more subtle than I expected. 

`TARGETID=2252857029951489` is one of the[ four problematic `HPM` targets that I already "turned off" earlier this year](https://github.com/desihub/desisurveyops/issues/109). It's HD 19467B.

When I "turned off" these targets in the ledger, I set their priorities to zero and also set their requested number of additional observations to zero. This is apparently insufficient for `fiberassign` not to put a fiber on a target. That makes sense, to some extent; `fiberassign` is likely mopping up with any available targets, even if that target has very low (zero) priority. Also, these targets will still have a non-zero value for `SUBPRIORITY`.

I don't really want to completely remove these problematic HPM targets from the ledgers, as if they were never there in the first place. Although, we _could_, of course. So, I think the question we need to answer is whether there's a value of `PRIORITY` (or some other parameter) that will completely prevent `fiberassign` from ever placing a fiber on a target. Any ideas?

**Comment by geordie666** [comment] 2023-12-25 11:22
A thought: I might be able to set the [`IN_BRIGHT_OBJECT` bit](https://github.com/desihub/desitarget/blob/2.7.0/py/desitarget/data/targetmask.yaml#L45) to turn off these targets. Although, I should check that `fiberassign` genuinely knows to avoid targets that have that bit set.

**Comment by schlafly** [comment] 2024-01-02 15:31
Does anything else have zero priority?  Are negative priorities allowed?  Does a sky fiber have a priority?  Just looking for options...

**Comment by araichoor** [comment] 2024-01-03 00:40
small temporary report (I ve to move to something else):

foreword:
in fiberassign, the `total_priority` is `100 * priority + obsremain + subpriority`.
(https://github.com/desihub/fiberassign/blob/a3356a341f55348371bb8514af8e810c8bb209ce/src/targets.cpp#L92)

then:
I confirm that this target has `PRIORITY=NUMOBS_MORE=0`, as reported by @geordie666.
also, I ve looked at the other potential targets for that fiber: apart from sky fibers, there also is a science target, `targetid=39627456281313352`.
though I m puzzled so far, as -- unless I m mistaking -- that other science target should have a higher `total_priority`.
so I don t understand as of now why that other target didn t get the fiber.
I ll dig more in the coming days.

for the record, looking at the mtl ledgers:

```
fiber = 1855
tid = 2252857029951489 # our HPM target
tid2 = 39627456281313352 # other potential target for fiber=1855
keys = ["TARGETID", "ZTILEID", "TARGET_STATE", "TIMESTAMP", "PRIORITY", "NUMOBS_MORE", "SUBPRIORITY", "TOTAL_PRIORITY"]
```

```
tiles = Table.read("/global/cfs/cdirs/desi/survey/fiberassign/main/005/005599-tiles.fits")
mtltime = fits.getheader("/global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/005/fiberassign-005599.fits.gz", 0)["MTLTIME"]
t = Table(read_targets_in_tiles("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/main/secondary/dark/", tiles=tiles, mtl=True, unique=True, isodate=mtltime))
t["TOTAL_PRIORITY"] = 100 * t["PRIORITY"] + t["NUMOBS_MORE"] + t["SUBPRIORITY"]
t[np.in1d(t["TARGETID"], [tid, tid2])][keys]
=>
     TARGETID     ZTILEID    TARGET_STATE            TIMESTAMP         PRIORITY NUMOBS_MORE    SUBPRIORITY       TOTAL_PRIORITY  
----------------- ------- ------------------ ------------------------- -------- ----------- ------------------ ------------------
 2252857029951489      -1 FAINT_HPM|OVERRIDE 2023-12-11T23:19:32+00:00        0           0 0.8193718197081896 0.8193718197081896
39627456281313352   10269   LOW_Z_TIER1|DONE 2023-12-11T23:18:59+00:00        2           0 0.5515090784182668 200.55150907841826
```

and, as a sanity check, reading the same info from the fiberassign intermediate file:
```
t = Table.read("/global/cfs/cdirs/desi/survey/fiberassign/main/005/005599-scnd.fits")
t["TOTAL_PRIORITY"] = 100 * t["PRIORITY"] + t["NUMOBS_MORE"] + t["SUBPRIORITY"]
t[np.in1d(t["TARGETID"], [tid, tid2])][keys]
=>
     TARGETID     ZTILEID    TARGET_STATE            TIMESTAMP         PRIORITY NUMOBS_MORE    SUBPRIORITY       TOTAL_PRIORITY  
----------------- ------- ------------------ ------------------------- -------- ----------- ------------------ ------------------
 2252857029951489      -1 FAINT_HPM|OVERRIDE 2023-12-11T23:19:32+00:00        0           0 0.8193718197081896 0.8193718197081896
39627456281313352   10269   LOW_Z_TIER1|DONE 2023-12-11T23:18:59+00:00        2           0 0.5515090784182668 200.55150907841826
```

**Comment by schlafly** [comment] 2024-01-03 01:42
I think the guess would be that the science target is blocked by a fiber collision with a neighboring fiber.

**Comment by araichoor** [comment] 2024-01-03 04:59
nice guess!

indeed that s what s happening:
- the neighboring positioner (fiber=1796, location=3522) is assigned to an unobs `ELG_LOP|UNOBS`:
```
     TARGETID     ZTILEID  TARGET_STATE         TIMESTAMP         PRIORITY NUMOBS_MORE     SUBPRIORITY       TOTAL_PRIORITY  
----------------- ------- ------------- ------------------------- -------- ----------- ------------------- ------------------
39627456277126177      -1 ELG_LOP|UNOBS 2021-05-13T08:15:37+00:00     3100           2 0.12087102795879756 310002.12087102793
```
- and that `TARGETID=39627456281313352` would collide with that `ELG_LOP` target; that s why it s not assigned to fiber=1855 (location=3509); with forcing some printing in the code:
```
INFO: check_collisions: tile 5599, loc 3509, target 39627456281313352 would collide with neighbor loc 3522, target 39627456277126177
INFO: check_collisions: tile 5599, loc 3509, target 2252857029951489 no collision with neighbor loc 3522, target 39627456277126177
```

and here s a plot with those three targets (those are the only science fibers reachable by those two positioners):
<img width="875" alt="Screenshot 2024-01-02 at 8 52 48 PM" src="https://github.com/desihub/desisurveyops/assets/61986357/66311673-7eea-4d7c-80e9-95d4045d689c">

so we understand everything here.
next step is to look if setting the `IN_BRIGHT_OBJECT` bit would help; I ll look into that.

**Comment by schlafly** [comment] 2024-01-03 13:41
Great, thanks!  I agree that the BRIGHT_OBJECT and IN_BRIGHT_OBJECT bits look promising from the documentation, at least...

**Comment by schlafly** [comment] 2024-01-08 23:07
Anand tried setting BRIGHT_OBJECT and IN_BRIGHT_OBJECT and fiberassign still wanted to assign this object.

@dstndstn , any interest in trying to figure out how we could set flags & priorities on this target to prevent it from getting assigned?  I think you're our expert on the inner workings on fiberassign.  According to Stephen, the original intent was that priority 0 targets never get assigned by fiberassign, but in practice this zero priority target continues to be assigned.  It's a hard case because there are no other science targets for the fiber; we'd prefer that it be assigned to some other (bad) sky fiber in the area.  In this and three other cases we know we've screwed up and accidentally put very bright targets in the target list, so we want to be able to tell fiberassign not to observe them, but we haven't been successful in doing that.

**Comment by dstndstn** [comment] 2024-01-10 21:22
Hi @araichoor, Eddie mentioned that you tried setting BRIGHT_OBJECT, IN_BRIGHT_OBJECT for this source -- do you happen to have the targeting files where you made that change?  No problem if you don't, I can hack the code to put it in.

I was reading through the code yesterday and it looked to me like that should have worked: those bits are in the `excludemask`
https://github.com/desihub/fiberassign/blob/main/py/fiberassign/targets.py#L310C32-L310C32
and then I thought they would set the `type` field to zero,
https://github.com/desihub/fiberassign/blob/main/py/fiberassign/targets.py#L660
and then it would get skipped when reading the targeting files into the C++ side,
https://github.com/desihub/fiberassign/blob/main/src/targets.cpp#L132

**Comment by araichoor** [comment] 2024-01-10 22:19
actually, you re right: I just tested `IN_BRIGHT_OBJECT`, and that works!
so it looks we could go for that.

sorry @schlafly, I ve not been precised during the telecon: what I actually did was to set `OBSCONDITIONS |= obsconditions["APOCALYPSE"]`, as I thought that would be equivalent.
but it s not, because of what @dstndstn wrote.

I only have quick-n-dirty test files, but let me share those, for the record..

So there are two tests, with hacking the fiberassign intermediate file `005599-scnd.fits`:
- `test_apocalypse` (that s the one I reported at the telecon): I set for that target `OBSCONDITIONS |= obsconditions["APOCALYPSE"]` => the problematic target still gets assigned; I suspect that s because there only are two science reachable targets, and the other one implies a collision with the neighboring positioner (assigned a `ELG_LOP` target);
- `test_inbright` (just done now): I set `DESI_TARGET |= desi_mask["IN_BRIGHT_OBJECT"]` => that works; the fiber=1855 is assigned to a (bad) sky; and the problematic target is absent from the list of reachable targets, consistent with the code reading from @dstndstn.

Now the files:
it s in this folder: `/global/cfs/cdirs/desi/users/raichoor/tmpdir/005/`:
- there I copied the "original" fiberassign intermediate products;
- then it s in  `test_apocalypse/` and `test_inbright/`.

The modified `005599-scnd.fits` files are created with:
```
from desitarget.targetmask import obsconditions, desi_mask

tid = 2252857029951489

d = Table.read("005599-scnd.fits")
d["OBSCONDITIONS"][d["TARGETID"] == tid] += obsconditions["APOCALYPSE"]
d.write("test_apocalypse/005599-scnd-apocalypse.fits")

d = Table.read("005599-scnd.fits")
d["DESI_TARGET"][d["TARGETID"] == tid] += desi_mask["IN_BRIGHT_OBJECT"]
d.write("test_inbright/005599-scnd-inbright.fits")
```

And I do the run with:
```
def ar_run(mydir, scndfn):
    opts = ["--targets", "005599-targ.fits", scndfn, "005599-too.fits", "--overwrite", "--write_all_targets", "--dir", mydir, "--footprint", "005599-tiles.fits",  "--rundate", "2023-12-04T17:00:44+00:00", "--sky_per_petal", 
    "40", "--standards_per_petal", "10", "--sky_per_slitblock", "1", "--ha", "19.072475", "--ha", "19.072475", "--margin-pos", "0.05", "--margin-gfa", "0.4", "--margin-petal", "0.4", "--sky", "005599-sky.fits", "--gfafile", "005599-gfa.fits", "--lookup_sky_source", "ls"]
    run_assign_full(parse_assign(opts))

def ar_merge(mydir, scndfn):
    ag = {}
    ag["tiles"] = [5599]
    ag["columns"] = None
    ag["targets"] = ["005599-targ.fits", scndfn, "005599-too.fits"]
    ag["sky"] = ["005599-sky.fits"]
    ag["result_dir"] = mydir
    ag["copy_fba"] = False
    merge_results(ag["targets"], ag["sky"], ag["tiles"], result_dir=ag["result_dir"], columns=ag["columns"], copy_fba=ag["copy_fba"])

tid, fiber = 2252857029951489, 1855
scndfns = [
    "test_apocalypse/005599-scnd-apocalypse.fits",
    "test_inbright/005599-scnd-inbright.fits",
]

for scndfn in scndfns:
    mydir = os.path.dirname(scndfn)
    ar_run(mydir, scndfn)
    ar_merge(mydir, scndfn)

for scndfn in scndfns:
    fafn = os.path.join(os.path.dirname(scndfn), "fiberassign-005599.fits")
    d = Table.read(fafn, "FIBERASSIGN")
    assgn_tid = d["TARGETID"][d["FIBER"] == fiber][0]
    d = Table.read(fafn, "TARGETS")
    isreach = tid in d["TARGETID"]
    print("{}\t{}\t{}".format(mydir, assgn_tid, isreach))
```

which returns:
```
# CASE ASSGN_TID ISREACH
test_apocalypse	2252857029951489	True
test_inbright	616088208584737322	False
```

**Comment by geordie666** [comment] 2024-01-10 22:25
Excellent. I'll set `IN_BRIGHT_OBJECT` for this target and for the [three other problematic targets](https://github.com/desihub/desisurveyops/issues/166#issuecomment-1868937393). 

I won't get to this until tomorrow at this point, though (it's late where I am).

**Comment by schlafly** [comment] 2024-01-11 13:25
Awesome, thanks Dustin, Anand, Adam.

FWIW, Anand, I'm not an expert, but I had understood the obsconditions bitmask to be a list of conditions in which it's okay to observe a target.  It sounds surprising to me if one adds a condition where it's observable (or-ing in apocalypse) and that leads the target to not be observed in some other conditions.

But great, it looks like we have a route forward.  Thanks everyone!

**Comment by geordie666** [comment] 2024-01-11 15:22
OK, I've now set `DESI_TARGET` to `4613937818241073152` (`['IN_BRIGHT_OBJECT', 'SCND_ANY']`) for the problematic target mentioned in this thread (`TARGETID=2252857029951489`) and the other three problematic targets (`TARGETID`s of `2253357037125632`, `2253605423808512` and `2253417447686145`) we [previously uncovered](https://github.com/desihub/desisurveyops/issues/109#issuecomment-1514848150).

**Comment by schlafly** [comment] 2024-01-23 17:45
I forgot that we still need to decide to mark this tile good, or reprocess without petal 3, or what.  I think now we will _not_ reobserve this bad target, so the right thing to do is to reprocess 5599 after marking petal 3 as bad and reprocessing.  @geordie666 , do you agree?

**Comment by geordie666** [comment] 2024-01-23 17:50
Ah, yes. I closed this issue a bit too quickly!

I agree that as we will hopefully now not reobserve the bad target we should reprocess tile `5599` _after_ marking petal 3 as bad.

**Comment by schlafly** [comment] 2024-01-23 18:05
Thanks.  @akremin , @abhi0395 , could we mark P3 (all cameras) on exposures 20231213/209556, 20231213/209557, 20231214/209791, tileid 5599 as bad, and reprocess the tile without them?  Note that those three exposures are on two separate nights.  Thanks!

**Comment by abhi0395** [comment] 2024-01-25 22:53
@schlafly Reprocessing after marking P3 as bad for these exposures for tile 5599 is complete. I have updated the tsnr and nightqa. Please feel free to close the issue of things look fine to you.

**Comment by schlafly** [comment] 2024-02-05 17:06
Thanks, marked good, closing, sorry for the delay.

**Closed by schlafly** 2024-02-05 17:06 UTC
