### ISSUE TITLE
Tile 25744 has petals 3,4,9 rejected for large STARRMS

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#17] opened 2022-01-28 23:59 UTC
Most of the signal for tile 25744 comes from the exposure 20220121/00119660.  Petals 3,4,9 are rejected due to a large STARRMS > 0.20 (dispersion in the standard star model fits) from the file /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220121/00119660/exposure-qa-00119660.fits

PETAL_LOC  STARRMS  
--------- ----------
        0 0.14335816
        1 0.14170471
        2 0.07650502
        3 0.20699991
        4 0.25244614
        5 0.13656339
        6 0.10696009
        7 0.16174984
        8 0.12091315
        9 0.20128961

Could the cause of this be the standard star fitting being pulled by the very poor data in the previous exposure 20220120/00119533 on the same tile?

**Comment by schlafly** [comment] 2022-01-31 20:55
Linking the QA plot for completeness
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25744/20220127/tile-qa-25744-thru20220127.png

**Comment by julienguy** [comment] 2022-02-09 00:47
For petal 4 that shows large rms, the calibrated spectra do not present discontinuities at the boundary of cameras for all 3 exposures of tile 25744 and in particular for exposure 00119660. Could it be due to large positioning errors + an  unusual seeing ?

**Comment by schlafly** [comment] 2022-02-09 00:53
Transparency was reported to be good on that night, with decent seeing bouncing around between 1 and 1.5".  First exposure of the night, but skies were pretty dark.  It is the case that the observers reported that the focus was "a bit off", but I seem to think that this usually means tens of microns.

> 18:47 [01:47] Exp. 119660- Good - First tile of the night. A bit off focus and seeing a bit high (1.43). RMS of first correction move is around 4 (SO)
> Tile 25744, Exptime: 844.75, Airmass: 1.20, Sequence: DESI, Flavor: science, Program: BRIGHT

**Comment by julienguy** [comment] 2022-02-09 02:26
The guiding PSF has some peculiar triangular shape. Only 44% of light in fibers on average. If we are out of focus, could there be radial changes in the PSF?
https://data.desi.lbl.gov/desi/spectro/data/20220121/00119660/etc-00119660.png

**Comment by julienguy** [comment] 2022-02-09 02:42
I suspect we were out of focus. 

![Screenshot from 2022-02-08 18-41-02](https://user-images.githubusercontent.com/5192160/153111850-96370210-ee9d-49e6-becc-8af61cf3e490.png)

```
from astropy.table import Table
for spec in range(10) :
    t=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220121/00119660/cframe-r{spec}-00119660.fits","FIBERMAP")
    s=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220121/00119660/cframe-r{spec}-00119660.fits","SCORES")
    i=t["FIBERFLUX_R"]>10
    x=t["FIBER_X"][i]
    y=t["FIBER_Y"][i]
    ratio=s["MEDIAN_CALIB_COUNT_R"][i]/t["FIBERFLUX_R"][i]
    ratio /= np.median(ratio)
    plt.scatter(x,y,c=ratio,vmin=0.8,vmax=1.2)
plt.colorbar()
```

**Comment by schlafly** [comment] 2022-02-09 21:09
Thanks.  It looks like we need to mark this as bad in the offline pipeline.  @akremin, can you mark 119660 as bad so that it gets EFFTIME = 0 and reprocess this tile 25744, and then we need to clear its QA status in tiles-specstatus?

I hadn't used the SCORES extension before---that's obviously useful!  Aiming to be more self-sufficient in the future, can you confirm that:
- RAW_COUNT -> frame file values
- FFLAT_COUNT -> frame file values after applying fiberflat
- SKYSUB_COUNT -> sframe file values
- CALIB_COUNT -> cframe file values

I suspect that since the GFAs are on the edge, in terms of raw SNR, this tile is good on the edges and very good in the center, but I agree we don't want to deal with out-of-focus images and should just mark as bad.

**Comment by julienguy** [comment] 2022-02-09 22:39
yes

**Comment by akremin** [comment] 2022-03-19 00:00
The following have been performed:

- 119660 marked as bad
- removed all files associated with tile 25744 on 20220121
- removed all redshift files associated with tile 25744 on 20220127
- reran redshifts for 25744 on 20220127

The observation on 20220120 was flagged by David as low efftime. There were no other observations on 20220121, so after flagging this exposure there was nothing to rerun. The tile was also observed on 20220126, but it was a bad exposure that wasn't used. So the 20220127 is the only exposure remaining for this tile.

I think this is below the efftime threshold, but could be released for more observations.

**Comment by schlafly** [comment] 2022-03-21 20:45
Resetting to QA = none.  Confirmed that this tile now has EFFTIME_SPEC < GOALTIME in $DESI_SPECTRO_REDUX/daily/tiles.csv, so this should be scheduled for future observation.  Closing.

**Closed by schlafly** 2022-03-21 20:45 UTC
Labels: dailyops
