### ISSUE TITLE
Feature on petal 4 for 22432 and 25001 on 20230507 

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#115] opened 2023-05-09 17:53 UTC
On slide 25 and 26, looking at petal 4, one can notice a feature in the upper right corner plot (https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230507/tileqa-20230507.pdf). 
Can someone double check that this is not problematic ? Thanks.

**Comment by schlafly** [comment] 2023-05-15 15:45
FWIW, these look like this:
![image](https://github.com/desihub/desisurveyops/assets/1417841/72cf5306-6275-4462-b7a2-4682acefc10b)
The sframes look ~fine to me; P4 doesn't immediately stand out.  We'd need to dig in more.

**Comment by schlafly** [comment] 2023-06-20 14:05
These were inadvertently marked 'good' and committed to the MTL.  They should be part of a future reprocessing & reverting plan.

**Comment by rongpu** [comment] 2023-08-21 18:07
If it helps, here are the z>1.5 objects from 25001: https://www.legacysurvey.org/viewer/?ra=313.6377&dec=-9.9553&catalog=tmpf9uhpfrh&zoom=9. They are mostly on the outer edge of the petal. And attached are the spectra of 10 of the 19 objects at z>1.5.
[tmp-4.pdf](https://github.com/desihub/desisurveyops/files/12399485/tmp-4.pdf)
Not sure how to interpret them, but certainly the problem is not H-alpha.

**Comment by araichoor** [comment] 2023-08-21 18:17
I was typing a similar message :)
same, pdf with spectra for those 19 guys here: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-25001-thru20230507.pdf
=> those mostly are MWS_{BLUE,RED} targets.
and, as @rongpu, I m not sure to interpret those spectra...

I confirm their "specificity" seems to be their position on the focal plan: see here for this TILEID=25001 and TILEID=22432:

![tmp](https://github.com/desihub/desisurveyops/assets/61986357/8db17b54-ec37-4646-9bfe-4f0159c0457f)

those two tiles are few degrees apart; and they are the last two tiles of the night, happening after slewing to the sgc: https://data.desi.lbl.gov/desi/users/raichoor/main-status/skyseq/skyseq-20230507.png

**Comment by araichoor** [comment] 2023-08-21 18:33
I confirm there s nothing obvious in the spacewatch movie: https://data.desi.lbl.gov/desi/users/raichoor/main-status/spacewatch/spacewatch-20230507.mp4

checking the nightlog, the first expid of 25001 has been marked as "unsure", but nothing s critical here, apparently:
<img width="1355" alt="Screenshot 2023-08-21 at 11 28 05 AM" src="https://github.com/desihub/desisurveyops/assets/61986357/e7029ee3-4ab6-400e-9399-018992417308">

checking the per-petal reports on the tile-qa*pdf for petal=4, it looks like petal=4 is a bit worse than the other petals but nothing critical.

and I also checked for tileid=25001 the overal n(z) for petal=4 and petal!=4, and there s nothing obviously wrong (except this excess at z~1.5).

based on all of that, I d say, yes, let s accept the tiles (even though it s frustrating to not understand the reason for those z~1.5 at the edge of petal=4...)

**Comment by schlafly** [comment] 2023-08-22 00:51
Let's go ahead and call these bad.  I don't understand them but it has to be instrumental.  It hasn't repeated and it's a few months old, so it's not worth working too hard to figure out what went wrong here.

Let's mark 20230507, expid 179579-179581, tileid 25001, 22432, P4 as bad.  We don't know which of BRZ is bad, so let's just mark all of P4 bad.

**Comment by schlafly** [comment] 2023-09-05 13:14
Pinging this outstanding issue.

**Comment by abhi0395** [comment] 2023-09-06 18:44
@schlafly Marked P4 bad for expid 179579-179581, tileid 25001, 22432. Re-processed tiles, tsnr+nightqa rerun. @sbailey can re-mtl them.

updated tsnr+nightqa at:
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230507/

**Comment by schlafly** [comment] 2023-09-07 12:52
Thanks, yes, I agree that these look good for re-archiving & re-MTLing now.

**Comment by sbailey** [comment] 2023-09-08 18:47
@schlafly @geordie666 I have rearchived tiles 25001 and 22432 with
```
desi_archive_tilenight -n 20230507 -t 25001 --badpetals 4 --rearchive
desi_archive_tilenight -n 20230507 -t 22432 --badpetals 4 --rearchive
```

Passing off to @geordie666 for MTL update.

**Comment by geordie666** [comment] 2023-09-08 23:06
Tiles `25001` and `22432` have been re-updated in the MTL ledgers.

**Closed by geordie666** 2023-09-08 23:06 UTC
Labels: dailyops, redo-mtl
