### ISSUE TITLE
Bright tile 26068 has an entire petal with low effective time, not obvious why

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#31] opened 2022-03-18 20:26 UTC
Bright tile 26068 observed on 20220317 shows petal 4 has having an unusual low effective time. It's not obvious to me why that's the case. Redshifts look OK. I marked that tile as unsure.
![unsure-26068](https://user-images.githubusercontent.com/1848618/159078445-a71ee4d8-a3ab-4733-993d-2c253370b407.png)

**Comment by araichoor** [comment] 2022-03-18 22:27
quick guess: it s made of two exposures, so I suspect the petal=4 is discarded in one of the two exposures.
you d have to explore the exposure-qa-EXPID.fits files to find why.

**Comment by schlafly** [comment] 2022-03-21 22:14
I can confirm that 00126561 has NGOODFIB = 0.  STARRMS = 0.21, which is probably the one that causes problems.  Looking at the cframe scores extension following Julien's lead, we'd infer that this is ~badly out of focus?
![image](https://user-images.githubusercontent.com/1417841/159362196-8e2a4b13-de9b-4223-bcaa-0ccbcd0aae30.png)

That's consistent with the Grafana autofocus plot from that night
![image](https://user-images.githubusercontent.com/1417841/159371635-057a96df-163b-4ffa-994e-b29e63077834.png)
so maybe the only outstanding question would be why we didn't get a good initial autofocus correction.  Maybe just slightly too fast?  Night log reports some time lost in twilight and the observers were clearly trying to get on sky.

Recently these calibration plots have been useful for debugging; we could consider putting them in the nightly QA plots (maybe replacing the turbulence plots, which haven't been very useful since the turbulence corrections went in?).  Repeating that code snippet from Julien:
```
im = '00126561'
night = '20220317'
from astropy.table import Table
for spec in range(10) :
    t=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/{night}/{im}/cframe-r{spec}-{im}.fits","FIBERMAP")
    s=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/{night}/{im}/cframe-r{spec}-{im}.fits","SCORES")
    i=t["FIBERFLUX_R"]>10
    x=t["FIBER_X"][i]
    y=t["FIBER_Y"][i]
    ratio=s["MEDIAN_CALIB_COUNT_R"][i]/t["FIBERFLUX_R"][i]
    ratio /= np.median(ratio)
    plt.scatter(x,y,c=ratio,vmin=0.8,vmax=1.2)
plt.colorbar()
```
Relatedly, we should get the things that flag various petals onto the QA plots.

Anyway, we need to mark 126561 as bad.  @akremin, can you do this?  Fortuitously, even with only 126562 we'll consider the tile good overall.  Then I'll redo QA.

**Comment by akremin** [comment] 2022-03-31 05:35
126561 ha been marked as bad. I removed all spectra+redshift files for tile 26068 on that night and reran with just 126562. I also reran the tsnr and nightly_qa scripts.

Back to you, Eddie.

**Comment by schlafly** [comment] 2022-04-01 18:05
Thanks, I repeated the QA here.  Now the tile is done and marked complete.

**Closed by schlafly** 2022-04-01 18:05 UTC
Labels: dailyops
