### ISSUE TITLE
Tile 2295 on 20220211 has low throughput petals 2,4,7

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#23] opened 2022-02-12 18:47 UTC
Tile 2295 on 2022-02-11 has low throughput on petals 2,4,7 causing a smattering of fibers to be rejected on those petals.  Note this was observed with a very bright sky (sky=7!), although otherwise very good conditions (photometric, 0.9 arcsec seeing).
![tile-qa-2295-thru20220211](https://user-images.githubusercontent.com/7918018/153724166-db1001de-08bb-4dc0-b8a7-48c452019010.png)

**Comment by schlafly** [comment] 2022-02-12 18:58
The line at z=1.8 is also typical of sky residuals.  c.f.
https://github.com/desihub/desisurveyops/issues/10
I don't know how that would relate to the flux calibration, though.

**Comment by ashleyjross** [comment] 2022-02-12 21:49
The issues do result in quite a bit worse LRG redshift success than usual (>0.98 is typical): 0.95, 0.96, 0.95, 0.92, 0.98, 0.88, 0.84, 0.85, 0.93, 0.91

So, the petals with the alerts indeed have bad performance but all expect petal 4 are worse than usual.

**Comment by araichoor** [comment] 2022-02-14 22:24
before I forget, following Julien s remark, expid=122164 indeed has PETAL_LOC=2,4,7,9 rejected, as those have zero NGOODFIB in the PETALQA extension of the exposure-qa*fits files.
I ve not investigated further.

```
>>> Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220211/00122162/exposure-qa-00122162.fits","PETALQA")["NGOODFIB"].tolist()
[470, 443, 442, 415, 445, 447, 445, 393, 431, 445]
>>> Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220211/00122163/exposure-qa-00122163.fits","PETALQA")["NGOODFIB"].tolist()
[470, 443, 442, 415, 445, 447, 445, 393, 431, 445]
>>> Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220211/00122164/exposure-qa-00122164.fits","PETALQA")["NGOODFIB"].tolist()
[470, 443, 0, 415, 0, 447, 445, 0, 431, 0]
```

**Comment by julienguy** [comment] 2022-02-14 22:54
they have the QAFIBERSTATUS bit fibermask.BADPETALSTDSTAR, large calibration rms for that exposure.

**Comment by julienguy** [comment] 2022-02-14 23:04
Could it be another exposure where the telescope was out of focus?
![Screenshot from 2022-02-14 15-01-45](https://user-images.githubusercontent.com/5192160/153961360-e8b0f36b-5b3a-4d21-be27-4cf47a1726d2.png)

We may want to add a plot such as this one in the tile QA, maybe when we have BADPETALSTDSTAR in an exposure.

```
e=122164
from astropy.table import Table
for spec in range(10) :
    t=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220211/00{e}/cframe-r{spec}-00{e}.fits","FIBERMAP")
    s=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220211/00{e}/cframe-r{spec}-00{e}.fits","SCORES")
    i=t["FIBERFLUX_R"]>10
    x=t["FIBER_X"][i]
    y=t["FIBER_Y"][i]
    ratio=s["MEDIAN_CALIB_COUNT_R"][i]/t["FIBERFLUX_R"][i]
    ratio /= np.median(ratio)
    plt.scatter(x,y,c=ratio,vmin=0.8,vmax=1.2)
plt.colorbar()
```

**Comment by schlafly** [comment] 2022-02-14 23:29
Interesting.  Here's the autofocus results:
![image](https://user-images.githubusercontent.com/1417841/153963024-85ff4b7d-1e95-4fbd-8e8b-3c1eaa372d84.png)
2295 was observed from 4:00-5:15.  So autofocus didn't really like 112162 but thought that 122164 was great.  I am also now remembering that we very intentionally (I think?) do not adjust focus during splits, since we didn't want to have to potentially move the fibers, so this hour+ exposure could aggravate that.  But I would have hoped to see it in the autofocus plots.

The ETC doesn't look like it makes PNGs for subsequent exposures in splits.  The ETC FFRAC does vary through the exposures
![image](https://user-images.githubusercontent.com/1417841/153964166-36b12ef3-dbcd-4cd9-b8b5-5c73d0172282.png)
though not in a way that is obviously related to losing focus.

**Comment by schlafly** [comment] 2022-02-14 23:35
But yeah, I do think we should make visible which petals get thrown out and why.

The calibration plot is convincing to me that we were out of focus, even if autofocus disagrees (?!).  So let's go ahead and mark 20220211/166164 as bad and reprocess (@akremin).  That won't fix the sky gradients, so I think I'd still end up leaving this one in limbo.  But the exposure will still be considered done with 900 effective seconds.

**Comment by akremin** [comment] 2022-03-14 21:08
Exposure 122164 flagged as bad. Processed files removed. I also removed associated exposure files for things after joint standard star fitting and reran those. Redshifts also removed and rerun. Exposures/tiles files updated to reflect the removed exposure.

I won't close the issue since Eddie made a comment about sky gradients and leaving this in limbo, but the removal portion of this ticket is done.

**Comment by schlafly** [comment] 2022-03-21 20:37
I can confirm that 2295 QA now has 122164 removed.  The line of bad redshifts at z=1.8 persists, coupled with high sky alerts.  I'm closing this issue, as this TILEID is also mentioned as part of https://github.com/desihub/desisurveyops/issues/10, where it better belongs.

**Closed by schlafly** 2022-03-21 20:37 UTC
Labels: dailyops
