### ISSUE TITLE
Expid 158488, tile 5181 on 20221216 QA shows one petal missing, but Nightwatch positioning diagnostics look fine

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#86] opened 2022-12-18 20:19 UTC
![tile-qa-5181-thru20221216](https://user-images.githubusercontent.com/1065981/208317482-38422749-d1b7-4802-92a7-5a6ef024be79.png)
<img width="665" alt="1" src="https://user-images.githubusercontent.com/1065981/208317515-891b85b6-2c65-4956-ab05-24b2f9f5fded.png">

**Comment by dstndstn** [comment] 2022-12-18 20:23
Suspect this is caused by https://github.com/desihub/desispec/issues/1940

**Comment by schlafly** [comment] 2022-12-18 20:42
Let's leave as unsure and tag and assign to Marcelo.  When this is resolved
we'll reQA.

**Comment by araichoor** [comment] 2022-12-18 21:43
for info, from @marcelo-alvarez on slack:
"_I could not find the cause of a pipeline failure during preproc traceshift for exposure 158488 on camera b4, so I marked sp4 as bad and consequently tile [5181](https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/5181/20221216/tile-qa-5181-thru20221216.png) was processed without it (see [desipec/1940](https://github.com/desihub/desispec/issues/1940))._"

https://desisurvey.slack.com/archives/C01HNN87Y7J/p1671322332283719

**Comment by marcelo-alvarez** [comment] 2022-12-19 22:20
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/32470484/208537704-230eb976-c727-4aef-a806-517df76878bd.png">

This should now be done @schlafly please have a look.

**Comment by schlafly** [comment] 2022-12-19 22:59
Great, I've assigned this back to myself and will close when we have changed the QA to good.  Thanks!

**Comment by schlafly** [comment] 2022-12-21 10:21
I've marked this as good.  It should be picked up by the next archiving and then included in MTL updates.  Closing.

**Closed by schlafly** 2022-12-21 10:21 UTC
Labels: dailyops
