### ISSUE TITLE
Tile 20634 on 2023-04-29 rejects all petal 8

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#113] opened 2023-04-30 18:10 UTC
We're operating with only half of b8 right now due to a mis-behaving b8-B amplifier.  However, tile 20634 observed on 2023-04-29 rejects all fibers on petal 8 with QAFIBERSTATUS > 0 (bit 15 is set for all those fibers, which is LOWEFFTIME).

At first, I thought this might have to do with only 2 good standard stars remaining on this half-CCD, but that's also true for tile 24219 on the same night, which does not reject all fibers on this petal.

**Comment by djschlegel** [comment] 2023-04-30 18:11
![tile-qa-20634-thru20230429](https://user-images.githubusercontent.com/7918018/235369353-36eefb75-8e61-4aca-84a2-0065c9c1bfba.png)

**Comment by araichoor** [comment] 2023-04-30 18:27
I think it s expected, because there s a special handling in the case of only two standard stars: the pipeline accepts that case if the rms between the star measurements is below some threshold (0.05), which is not the case for tileid=20634 (but tileid=24219 is ok).

details:

for completeness, here s the tile-qa for tileid=24219, which also has two standard stars:
<img width="1206" alt="Screenshot 2023-04-30 at 11 15 14 AM" src="https://user-images.githubusercontent.com/61986357/235369523-fc6e9e02-6842-470d-bd94-564fba19de4d.png">
note that for 24219, there is no red "STDSTAR" mention in the BAD column.

here s the rms threshold of 0.05 for this 2-stdstars case:
https://github.com/desihub/desispec/blob/eb9f86e93c81c11792363121408231bc45b370c7/py/desispec/data/qa/qa-params.yaml#L18-L26
```
 # maximum rms of calibration error per star
 # (ratio of calibrated flux to model in rband)
 max_rms_of_rflux_ratio_of_stdstars : 0.2


 # maximum rms of calibration error per star
 # (ratio of calibrated flux to model in rband)
 # in case there are less than the min number of stars
 # (in practice 2 stars). The requirement is more strict
 max_rms_of_rflux_ratio_of_stdstars_if_few_stars : 0.05
```
(code here: 
 https://github.com/desihub/desispec/blob/eb9f86e93c81c11792363121408231bc45b370c7/py/desispec/exposure_qa.py#L287-L290)

**Comment by schlafly** [comment] 2023-05-01 17:41
I agree that this is by design and that we should mark this tile as good.  An action item would be to make sure that the standard stars / skies end up on the good half of the CCD, depending on how long we think b8B is going to be out of action.

**Comment by schlafly** [comment] 2023-05-30 15:45
We ended up replacing b8 pretty quickly and didn't do this.  Closing.

**Closed by schlafly** 2023-05-30 15:45 UTC
