### ISSUE TITLE
Concentration of high confidence sky fiber redshifts at fiberid ~2500

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#94] opened 2023-01-10 19:30 UTC
Starting January 2023, sky fibers with fiberid ~ 2500 are given confident redshifts (Delta Chi2 > 9) at z~1.6. It shows up quite clearly on 20230108 for bright tiles: https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230108/skyzfiber-20230108.png

(I will try to add more specifics soon.)

**Comment by ashleyjross** [comment] 2023-01-10 23:51
Looks concentrated to the first 100 fibers on petal 5 and the redshifts are at a number of attractors. 
<img width="368" alt="Screen Shot 2023-01-10 at 6 50 06 PM" src="https://user-images.githubusercontent.com/14100086/211686212-a35ac0be-8469-404c-915e-0c34b18aebd5.png">
<img width="414" alt="Screen Shot 2023-01-10 at 6 49 50 PM" src="https://user-images.githubusercontent.com/14100086/211686217-63462a16-3975-437d-8806-d4dda34320e0.png">

**Comment by ashleyjross** [comment] 2023-01-10 23:54
And the confident ones are very much at the attractors:
<img width="395" alt="Screen Shot 2023-01-10 at 6 53 41 PM" src="https://user-images.githubusercontent.com/14100086/211686555-aef94f4b-78ce-418d-b052-a84ec8ff6f8e.png">

**Comment by ashleyjross** [comment] 2023-01-11 01:10
<img width="564" alt="Screen Shot 2023-01-10 at 8 09 54 PM" src="https://user-images.githubusercontent.com/14100086/211694725-f628c5bb-04a5-44bc-a92e-a73d6842004d.png">
There is a feature at around 3800 in these spectra

**Comment by ashleyjross** [comment] 2023-01-11 04:06
It looks like they do to me. I'm not sure how to prove it is the issue...

**Comment by schlafly** [comment] 2023-01-19 16:32
Closing this as a duplicate of https://github.com/desihub/desisurveyops/issues/93 .

**Closed by schlafly** 2023-01-19 16:32 UTC
