### ISSUE TITLE
Tiles from 20240627 marked unsure due to possible r1 reset.

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#201] opened 2024-06-28 19:21 UTC
The r1 dark (attached) from 20240627 shows instability that may be due to a ccd restart. Because of this all 14 tiles observed from that night: [1508, 2871, 4557, 4559, 6601, 6617, 9062, 9542, 9713, 10772, 11105, 11269, 21587, 23446] are marked as unsure.

![20240627-r1dark](https://github.com/desihub/desisurveyops/assets/17151647/9e32d35f-8baf-4285-83e4-68fbd051fdac)

**Comment by schlafly** [comment] 2024-07-22 15:59
Let's call r1 bad on 20240627 from the start of the night through expid 240348, for bright & dark tiles.  That's expid 240328 through 240348, on tileid 23346, 5936, 21587, 9542, 11105, 9062, 11129, 4557, 10772, 4559, 9713, 6617, 6601, 1508.  The redshifts actually look pretty fine, but P1 does look to have lower redshift success and there are clear residuals on the sframes.

**Comment by abhi0395** [comment] 2024-07-22 20:35
@schlafly I am working on it. One issue to note is that two tiles (5936 expid 240334 and 11129, expid 240339) were also observed on 20240629 and possibly they were marked good and archived. So I get the permission error for them while purging after marking "r1" as bad for 20240627. Please suggest how to proceed for them. For all other tiles, I am working as usual.

**Comment by akremin** [comment] 2024-07-22 20:43
For the record I confirmed in the `tiles-specstatus.ecsv` file that they were mistakenly archived on 0702:
```
TILEID SURVEY FAPRGRM FAFLAVOR NEXP EXPTIME TILERA TILEDEC EFFTIME_ETC EFFTIME_SPEC EFFTIME_GFA GOALTIME OBSSTATUS ZDONE LRG_EFFTIME_DARK ELG_EFFTIME_DARK BGS_EFFTIME_BRIGHT LYA_EFFTIME_DARK GOALTYPE MINTFRAC LASTNIGHT QA USER OVERRIDE QANIGHT ARCHIVEDATE
5936 main dark maindark 3 2396.4 230.183 29.597 2023.7 999.8 0.0 1000.0 obsend true 999.8 900.7 1017.9 1210.6 dark 0.85 20240629 good LGN 0 20240629 20240702
11129 main dark maindark 4 2218.7 245.121 29.765 734.9 881.4 948.4 1000.0 obsend true 881.4 826.6 916.9 933.4 dark 0.85 20240629 good LGN 1 20240629 20240702
```

**Comment by schlafly** [comment] 2024-08-06 16:01
On the survey-ops call we decided to mark these two exposures as bad and to force reobservation of 11129 manually.  We can rearchive & reMTL them after that.  Let's go ahead and do that.  @akremin , back to you?

**Comment by akremin** [comment] 2024-08-06 22:15
Thanks Eddie, yes back to me. I believe I can re-archive but I would prefer to wait for @sbailey to return from vacation before proceeding with this, since he has been the one historically who did the re-archiving and I'd like to have him available just in case. If it's alright with you let's leave these as-is for another week and then I can deal with them.

**Comment by schlafly** [comment] 2024-08-15 08:19
Ah, right, perfect.  Yes, let's go ahead.

**Comment by geordie666** [comment] 2024-08-15 16:44
Yep, I think we should go ahead.

I didn't quite parse Anthony's comment about "the archive date for both is 20240629 because more data was taken on that date."

The current archive date for both 5936 and 11129 is `20240702`. I'd hope that the next archive date will be, e.g., `20240815`. My mild concern is that I think my MTL-re-processing code requires the re-processing archive date to be later than the initial archive date.

**Comment by akremin** [comment] 2024-08-15 22:06
Sorry I just meant that we got more data on 0629, which is after the night
impacted by the r1 issue. So the cumulative redshifts in the 20240629
directories are the ones we want to archive.

I used the wrong terminology, I think archive date is the date we archived
the processed files, which based on your post happened on July 2nd.

**Comment by geordie666** [comment] 2024-08-15 22:08
Great, then I think we should go ahead and re-archive before re-MTL-processing. I'll be mostly out of communication until tomorrow, though, if we want to coordinate this carefully.

**Comment by sbailey** [comment] 2024-08-27 21:16
Thanks for the ping; this had fallen off my radar.  I archived these two tiles with
```
desi_archive_tilenight -t 5936 --rearchive
desi_archive_tilenight -t 11129 --rearchive
svn commit -m "Rearchived tiles 5936 and 11129" $DESI_ROOT/survey/ops/surveyops/trunk/ops/tiles-specstatus.ecsv
```

I'll leave it to @schlafly or equivalent to do the final sign off and close the ticket.

**Comment by geordie666** [comment] 2024-08-27 21:22
I'll sign off on this and close the ticket once I re-MTL.

**Comment by geordie666** [comment] 2024-08-28 00:25
I have reprocessed the MTLs for tiles 5936 and 11129. The relevant command (in the `gomtl` environment) is simply:

```
 run_mtl_loop DARK --reprocess
```
I'll document this later tonight.

Closing the ticket, as I think we're done here.

**Closed by geordie666** 2024-08-28 00:25 UTC
