### ISSUE TITLE
Running dailyops on Perlmutter

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#73] opened 2022-11-03 21:47 UTC
Has anyone successfully run dailyops on Perlmutter? I'm getting this error message when loading the desisurveyops environment:
```
rongpu@login18:~> source /global/common/software/desi/desi_environment.sh master
rongpu@login18:~> module load desisurveyops/main
Lmod has detected the following error:  The following module(s) are unknown: "desisurveyops/main"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "desisurveyops/main"

Also make sure that all modulefiles written in TCL start with the string #%Module
```

I stopped there and will stick to Cori for next week's dailyops, but it might be good to start the discussion on transitioning to Perlmutter.

**Comment by araichoor** [comment] 2022-11-03 21:57
thanks Ronpgu!

with looking 2min:
it looks like on cori `module load desisurveyops/main` is related to this file: `/global/common/software/desi/cori/desiconda/20211217-2.0.0/modulefiles/desisurveyops/main`

and such a `desisurveyops/main` file does not exist in the equivalent perlmutter location:
```
raichoor@perlmutter:login27:~> ls /global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/modulefiles/
desiconda  desimodel	     desispec	 desitransfer  dust	    gpu_specter  QuasarNP	    simqso    specsim
desietc    desisim	     desisurvey  desitree      fastspecfit  nightwatch	 redrock	    specex    specter
desimeter  desisim-testdata  desitarget  desiutil      fiberassign  prospect	 redrock-templates  speclite  surveysim
```

**Comment by sbailey** [comment] 2022-11-03 22:00
I just installed desisurveyops/main on perlmutter.  Please try again, also using "desi_environment.sh main" instead of "master" (and please correct any docs that mentioned "desi_environment.sh master")

**Comment by rongpu** [comment] 2022-11-03 22:12
@sbailey Thanks. I can load desisurveyops now. Do you (or anyone) foresee other issues with running dailyops on Perlmutter? If not, I can try doing it next Monday.

**Comment by schlafly** [comment] 2022-11-04 17:03
Please go ahead and try.  Honestly, I thought I had already tried this!

**Comment by rongpu** [comment] 2022-11-09 19:34
Another problem: on Perlmutter I cannot run the `collabsu` command (needed for the fiberassign reproducibility check): https://docs.nersc.gov/systems/perlmutter/#connecting-to-perlmutter-with-a-collaboration-account

**Comment by sbailey** [comment] 2022-11-09 19:36
The replacement for collabsu is *on your laptop* run `sshproxy.sh -c desi` and then `ssh desi@perlmutter-p1.nersc.gov`.  If your copy of sshproxy.sh doesn't recgonize -c, grab the latest version.  Please update any surveyops wiki instructions that still mention collabsu.

**Comment by schlafly** [comment] 2022-11-09 19:36
Yeah, this works, but you have to do it via the way the describe at your link.

**Comment by araichoor** [comment] 2022-11-09 19:38
just checking, in case it s relevant: these lines connect as `desiproc`?

**Comment by schlafly** [comment] 2022-11-09 19:45
FWIW, I just updated the DailyOps page to have a collaboration accounts section.

**Comment by akremin** [comment] 2022-11-09 20:02
@araichoor I believe you'd use `sshproxy.sh -c desiproc` in that case. The command is specific to the collaboration account you're trying to access.

**Comment by sbailey** [comment] 2022-11-10 00:13
One more detail:
```
ssh -Y -i $HOME/.ssh/desiproc desiproc@perlmutter-p1.nersc.gov
```
i.e. you have to tell ssh which key to use

**Comment by rongpu** [comment] 2022-11-10 00:29
Thanks, that works. I have added these commands to the DailyOps page.

**Comment by geordie666** [comment] 2022-12-08 19:12
@rongpu: Can we close this issue?

**Comment by rongpu** [comment] 2022-12-08 19:17
I didn't end up running the full dailyops procedures on Perlmutter during my shift. But if you or anyone have successfully run the procedures on Perlmutter, then we should close it.

**Comment by geordie666** [comment] 2022-12-08 19:19
Ah, makes sense, thanks for the note. Maybe we should wait until we're back in a more normal mode of survey operations, where we run through all the steps one-by-one. Everything's a tad asynchronous at the moment!

**Comment by geordie666** [comment] 2022-12-10 14:44
I've now tried all of the daily operations steps on Perlmutter, including:

- Fiberassign reproducibility.
- Tile QA.
- Archiving tiles.
- MTL.

and I confirm that everything works. So, I'm closing this issue.

**Closed by geordie666** 2022-12-10 14:44 UTC
Labels: dailyops
